version: "3.8"
services:
  redis:
    image: redis:latest
    #container_name: redis-strategy
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 16379:6379

  localDB:
    image: mysql:8.0.30
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul

