logging:
  level:
    root: info

spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 16379








